package com.ticketing.model;

public enum TicketActivityType {
    TICKET_CREATED,
    TICKET_UPDATED,
    TICKET_PROMOTED,
    PHASE_TRANSITIONED,
    TICKET_COMPLETED,
    TICKET_CANCELLED,
    TICKET_REASSIGNED,
    IDEA_ADDED,
    IDEA_UPDATED,
    IDEA_DELETED,
    CHECKPOINT_TOGGLED,
    COMMENT_ADDED,
    ATTACHMENT_UPLOADED,
    ATTACHMENT_DELETED,
    RELATED_TICKET_LINKED,
    RELATED_TICKET_UNLINKED
}
